import "@fortawesome/fontawesome-free/css/all.min.css";
import "../styles/custom.scss";
import "../styles/index.scss";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
